# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"open_data": "00_dataloader.ipynb",
         "transform_data": "00_dataloader.ipynb",
         "get_labels": "00_dataloader.ipynb",
         "dataloader": "00_dataloader.ipynb",
         "sentence_embeds_model": "01_model.ipynb",
         "context_classifier_model": "01_model.ipynb",
         "metrics": "01_model.ipynb",
         "f1_score": "01_model.ipynb",
         "EmotionModel": "02_lightning.ipynb",
         "get_args": "02_lightning.ipynb",
         "main": "02_lightning.ipynb"}

modules = ["dataloader.py",
           "model.py",
           "core.py"]

git_url = "https://github.com/juliusberner/emotion_transformer/tree/master/"

def custom_doc_links(name): return None
